# -*- coding: utf-8 -*-
"""An NLP Deep Dive into Yoruba-English Code-Switching

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SOItClMCRQvVm2bQ9-horGlVQUflZ8gr
"""

# ============================================================
# CELL 0 — Install packages + download FastText model
# ============================================================
# Run this cell ONCE when you first open the notebook.
# After it finishes, go to Runtime → Restart session,
# then start from Cell 1.
# You do NOT need to re-run this cell in future sessions
# unless you open a brand-new Colab runtime.
# ============================================================

import subprocess, os, urllib.request

# Install all Python packages the pipeline needs
subprocess.run([
    "pip", "install", "-q",
    "openai", "langchain", "langchain-openai", "langchain-core",
    "pandas", "matplotlib", "tqdm", "gradio", "fasttext",
    "sentence-transformers", "scikit-learn", "umap-learn"
], check=True)

# Download the FastText language-identification model (~126 MB).
# This file must exist in the Colab working directory before Cell 7 runs.
FASTTEXT_PATH = "lid.176.bin"
if not os.path.exists(FASTTEXT_PATH):
    print("Downloading FastText lid.176.bin (~126 MB)...")
    urllib.request.urlretrieve(
        "https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin",
        FASTTEXT_PATH
    )
    print("Download complete.")
else:
    print(f"'{FASTTEXT_PATH}' already present -- skipping download.")

print("\nCell 0 done. Now go to Runtime → Restart session, then run Cell 1.")

# ============================================================
# CELL 1 — Shared setup: imports, config, helpers
# ============================================================
# Run this cell ONCE at the start of every Colab session,
# before running any other cell. It loads libraries, defines
# all configuration constants, and registers all helper
# functions into memory. It does NOT call any of them.
#
# Every other cell depends on this one being in memory.
# If your session times out and variables are lost, just
# re-run this cell before re-running whichever cell you need.
# ============================================================

import json, os, time, urllib.request
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.patches import Patch
from tqdm import tqdm
from google.colab import userdata
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.caches import InMemoryCache
from langchain_core.globals import set_llm_cache
from langchain_openai import ChatOpenAI
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from umap import UMAP
import gradio as gr
import fasttext

# ── Configuration ────────────────────────────────────────────
# Edit only this block if you want to change generation targets
# or file paths. Everything else in the pipeline is derived
# automatically from these constants.

SENTENCES_PER_THEME = 10   # how many sentences to generate per theme

THEMES = [
    {
        "name": "sport",
        "directions": (
            "rugby tackles and scrums, football (soccer) matches and player transfers, "
            "basketball games and NBA players, cricket innings and wickets, "
            "local Nigerian leagues, stadium experiences, sports betting, "
            "injuries and training sessions"
        ),
    },
    {
        "name": "health",
        "directions": (
            "malaria and typhoid symptoms, hospital visits and waiting rooms, "
            "drug prescriptions and pharmacies, vaccine drives and immunisation, "
            "gym workouts and fitness goals, mental health conversations, "
            "blood pressure and diabetes management, traditional herbal medicine"
        ),
    },
    {
        "name": "finance",
        "directions": (
            "mobile money transfers via Opay, PalmPay or Kuda, bank loan applications, "
            "market sales and price haggling, stock market and investments, "
            "saving contributions (ajo/esusu), fuel price complaints, "
            "salary delays, business profit and loss"
        ),
    },
    {
        "name": "general",
        "directions": (
            "family gatherings and celebrations, helping parents at home, "
            "church and mosque attendance, hobbies like cooking and sewing, "
            "neighbourhood gossip, wedding planning, baby naming ceremonies, "
            "arguments with siblings, watching TV together"
        ),
    },
    {
        "name": "school_subjects",
        "directions": (
            "biology practicals and dissections, mathematics formulas and homework, "
            "psychology theories and human behaviour, chemistry experiments, "
            "history lessons about Nigeria, literature comprehension passages, "
            "physics problems, geography field trips"
        ),
    },
]

# Derived from THEMES and SENTENCES_PER_THEME -- do not edit these
CANDIDATES_TARGET = len(THEMES) * SENTENCES_PER_THEME   # 50 total

# Output file paths -- all files land in the Colab working directory
CANDIDATES_FILE   = "candidates.csv"
APPROVED_FILE     = "approved_sentences.csv"
NER_FILE          = "ner_output.csv"
POS_FILE          = "pos_output.csv"
NER_VERIFIED_FILE = "ner_verified.csv"
LANGID_FILE       = "langid_output.csv"
FASTTEXT_PATH     = "lid.176.bin"

# Colour palette shared across all visualisations
THEME_PALETTE = {
    "sport":           "#2A9D8F",
    "health":          "#E9C46A",
    "finance":         "#378ADD",
    "general":         "#7F77DD",
    "school_subjects": "#D85A30",
    "unknown":         "#888780",
}

# ── LLM setup ────────────────────────────────────────────────
# Your OpenAI key must be stored in Colab Secrets under the
# name OPENAI_API_KEY (click the key icon in the left sidebar).
api_key = userdata.get("OPENAI_API_KEY")
llm = ChatOpenAI(openai_api_key=api_key, model_name="gpt-4", temperature=0.7)
set_llm_cache(InMemoryCache())  # prevents duplicate API calls within a session

# ── Prompt templates ─────────────────────────────────────────
generation_prompt = ChatPromptTemplate.from_template(
"""
You are helping build an NLP dataset of Yoruba-English code-switched sentences.

Generate {num_examples} UNIQUE code-switched sentences on the theme: {theme}
Suggested directions within this theme: {directions}

Rules every sentence must follow:
- Between 6 and 10 words long
- Must naturally blend Yoruba AND English words within the same sentence
  (not full Yoruba or full English -- genuinely mixed)
- Must include at least one named entity: a person name (e.g. Tunde, Amaka, Bola,
  Chidi, Kemi), a place (e.g. Lagos, Ibadan, Abuja, Kano), or an organisation
  (e.g. GTBank, UNILAG, LASUTH, MTN, Zenith Bank)
- Must be realistic and conversational, as if overheard in everyday Nigerian life
- Must be clearly within the stated theme -- do NOT drift into banking or money
  transfer unless the theme specifically calls for it

Return ONLY a JSON array. Each item must have exactly one key:
{{ "sentence": "..." }}

No explanation. No markdown. No preamble. Just the raw JSON array.
"""
)

annotation_prompt = ChatPromptTemplate.from_template(
"""
You are an NLP expert. Given these code-switched Yoruba-English sentences,
perform two annotation tasks simultaneously:

1. Named Entity Recognition (NER) -- tag entities as:
   - PERSON (people's names, e.g. Tunde, Amaka, Bola)
   - LOCATION (places, cities, countries, e.g. Lagos, Ibadan, Nigeria)
   - ORGANIZATION (companies, schools, banks, e.g. GTBank, UNILAG, MTN)

2. Part-of-Speech (POS) tagging -- tag every word using Universal Dependencies tags:
   NOUN, VERB, ADJ, ADV, PRON, DET, ADP, CONJ, INTJ, PROPN, NUM, PUNCT,
   X (for foreign or unclassifiable words)

Sentences:
{sentences}

Return ONLY a JSON array. Each item must have BOTH annotation layers:
{{
  "sentence": "...",
  "entities": [ {{ "word": "...", "label": "..." }} ],
  "pos_tags": [ {{ "word": "...", "pos": "..." }} ]
}}

If a sentence has no named entities, return an empty list for "entities".
No explanation. No markdown. Just the JSON array.
"""
)

# ── Helper functions ─────────────────────────────────────────
# These small utilities are used across multiple cells, so they
# are defined here once and loaded into memory from Cell 1.

def call_llm(messages, retries=3, wait_time=2):
    """Invoke GPT-4 with exponential backoff on transient failures."""
    for attempt in range(retries):
        try:
            return llm.invoke(messages).content
        except Exception as e:
            print(f"  Attempt {attempt + 1} failed: {e}")
            time.sleep(wait_time * (attempt + 1))  # 2s, 4s, 6s
    print("  All retries exhausted.")
    return None

def parse_json_output(output: str):
    """Strip markdown fences GPT-4 sometimes adds, then parse JSON."""
    clean = (
        output.strip()
        .removeprefix("```json").removeprefix("```")
        .removesuffix("```").strip()
    )
    return json.loads(clean)

def load_or_create(filepath: str, columns: list) -> pd.DataFrame:
    """Load a CSV checkpoint if it exists, or return an empty DataFrame."""
    try:
        df = pd.read_csv(filepath)
        print(f"  Loaded '{filepath}': {len(df)} rows.")
        return df
    except FileNotFoundError:
        print(f"  '{filepath}' not found -- starting fresh.")
        return pd.DataFrame(columns=columns)

def get_embedding_model():
    """Load the multilingual sentence embedding model (cached after first load)."""
    if not hasattr(get_embedding_model, "_model"):
        print("  Loading sentence embedding model (first call only)...")
        get_embedding_model._model = SentenceTransformer(
            "paraphrase-multilingual-MiniLM-L12-v2"
        )
    return get_embedding_model._model

def ensure_fasttext():
    """Auto-download lid.176.bin if it is not in the working directory."""
    if not os.path.exists(FASTTEXT_PATH):
        print(f"  '{FASTTEXT_PATH}' not found. Downloading (~126 MB)...")
        urllib.request.urlretrieve(
            "https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.bin",
            FASTTEXT_PATH
        )
        print("  Download complete.")

def dark_ax(ax):
    """Apply consistent dark-mode styling to a matplotlib axis."""
    ax.set_facecolor("#1A1A2E")
    ax.tick_params(colors="white")
    ax.xaxis.label.set_color("white")
    ax.yaxis.label.set_color("white")
    ax.title.set_color("white")
    for spine in ax.spines.values():
        spine.set_edgecolor("#444")

print("Cell 1 ready. All imports, config, and helpers are loaded.")
print(f"Pipeline target: {CANDIDATES_TARGET} sentences across {len(THEMES)} themes.")

# ============================================================
# CELL 2 — Generate 50 candidate sentences (10 per theme)
# ============================================================
# Prerequisites : Cell 1 has been run this session
# Reads         : nothing (starts fresh or resumes from candidates.csv)
# Writes        : candidates.csv
#
# This cell is permanently locked once candidates.csv contains
# 50 rows. Re-running it after that does nothing. If a theme
# already has its 10 sentences saved from a previous run, that
# theme is skipped and only the missing themes are generated.
# ============================================================

def generate_candidates():
    df = load_or_create(CANDIDATES_FILE, ["sentence", "theme", "status"])

    if len(df) >= CANDIDATES_TARGET:
        print(f"Generation already complete: {CANDIDATES_TARGET} sentences exist.")
        return df

    print(f"Generating {SENTENCES_PER_THEME} sentences per theme "
          f"({len(THEMES)} themes = {CANDIDATES_TARGET} total)...\n")

    for theme in THEMES:
        name       = theme["name"]
        directions = theme["directions"]
        already    = int((df["theme"] == name).sum()) if "theme" in df.columns else 0

        if already >= SENTENCES_PER_THEME:
            print(f"  [{name}] already complete ({already} sentences). Skipping.")
            continue

        needed   = SENTENCES_PER_THEME - already
        print(f"  [{name}] requesting {needed} sentences from GPT-4...")
        messages = generation_prompt.format_messages(
            num_examples=needed, theme=name, directions=directions
        )
        output = call_llm(messages)
        if output is None:
            print(f"  [{name}] API call failed. Skipping theme.")
            continue

        try:
            data = parse_json_output(output)
        except Exception as e:
            print(f"  [{name}] Parse error: {e}. Skipping theme.")
            continue

        rows = [
            {"sentence": item.get("sentence", "").strip(),
             "theme": name, "status": "pending"}
            for item in data if item.get("sentence", "").strip()
        ][:needed]  # trim to exactly what was requested

        if rows:
            df = pd.concat([df, pd.DataFrame(rows)], ignore_index=True)
            df.to_csv(CANDIDATES_FILE, index=False)
            print(f"  [{name}] saved {len(rows)} sentences.")
        else:
            print(f"  [{name}] no valid sentences returned by GPT-4.")

    print(f"\nTotal in '{CANDIDATES_FILE}': {len(df)}")
    print("Next step: run Cell 3 (semantic space visualisation).")
    return df

# ── Run ──────────────────────────────────────────────────────
candidates_df = generate_candidates()

# ============================================================
# CELL 4 — Human quality review (Keep / Reject)
# ============================================================
# Prerequisites : Cell 1 has been run this session
# Reads         : candidates.csv
# Writes        : approved_sentences.csv  (updated after every click)
#                 candidates.csv          (status column updated)
#                 quality_review_report.png
#
# Uses ipywidgets instead of Gradio. ipywidgets is part of the
# Jupyter/Colab kernel protocol, so it always renders directly
# inside the cell output -- no URL, no tunnel, no loading wait.
#
# Progress is saved to disk after every single click so a dropped
# session loses at most one judgment. Re-running this cell resumes
# from where you left off -- already-reviewed sentences are skipped.
#
# When the last sentence is reviewed the buttons disable themselves
# and metrics + infographic are generated automatically.
# ============================================================

import ipywidgets as widgets
from IPython.display import display, clear_output

def launch_rating_ui():

    approved_df = load_or_create(APPROVED_FILE, ["sentence", "theme", "notes"])

    try:
        candidates_df = pd.read_csv(CANDIDATES_FILE)
    except FileNotFoundError:
        print("candidates.csv not found. Run Cell 2 first.")
        return None

    pending_mask = candidates_df["status"] == "pending"

    if not pending_mask.any():
        print("All sentences already reviewed.")
        _print_review_metrics()
        return approved_df

    pending_rows = candidates_df[pending_mask].reset_index(drop=True)

    state = {
        "idx":         0,
        "rows":        pending_rows,
        "kept":        len(approved_df),
        "rejected":    int((candidates_df["status"] == "rejected").sum()),
        "approved_df": approved_df,
    }

    # ── Build the widget layout ───────────────────────────────────────────────
    # Each widget is a single UI element. We update their .value properties
    # in-place whenever a decision is made, which causes Colab to re-render
    # them without rebuilding the whole interface.

    title = widgets.HTML(
        "<h3 style='margin:0 0 4px 0; color:#e0e0e0'>"
        "Yoruba-English Code-Switch: Quality Review</h3>"
        "<p style='margin:0 0 12px 0; color:#aaaaaa; font-size:13px'>"
        "Press <b>Keep</b> if the sentence is natural and genuinely code-switched. "
        "Press <b>Reject</b> if it feels unnatural, is mostly one language, "
        "or is a near-duplicate of something you have already kept. "
        "No quota -- keep what is good.</p>"
    )

    # The sentence is displayed in a styled HTML box so we can control
    # the font size and background without being constrained by Textbox styling
    sentence_display = widgets.HTML()

    theme_badge   = widgets.HTML()
    progress_info = widgets.HTML()

    notes_input = widgets.Textarea(
        placeholder="Optional note (e.g. reason for rejection)",
        layout=widgets.Layout(width="100%", height="56px"),
    )

    keep_btn = widgets.Button(
        description="✓  Keep",
        button_style="success",          # green
        layout=widgets.Layout(width="140px", height="44px"),
    )
    reject_btn = widgets.Button(
        description="✗  Reject",
        button_style="danger",           # red
        layout=widgets.Layout(width="140px", height="44px"),
    )

    # This output widget captures anything printed inside the callback,
    # including the final metrics summary, and displays it below the buttons
    output_area = widgets.Output()

    def refresh():
        """Update all displayed values to match the current sentence in the queue."""
        if state["idx"] >= len(state["rows"]):
            sentence_display.value = (
                "<div style='padding:12px; background:#1A3A1A; border-radius:6px; "
                "color:#1D9E75; font-size:15px; font-weight:bold'>"
                "All sentences reviewed!</div>"
            )
            theme_badge.value   = ""
            progress_info.value = (
                f"<span style='color:#aaaaaa; font-size:13px'>"
                f"Done — Kept: <b>{state['kept']}</b>  "
                f"Rejected: <b>{state['rejected']}</b></span>"
            )
            keep_btn.disabled   = True
            reject_btn.disabled = True
            notes_input.disabled = True
            # Trigger metrics and infographic automatically on completion
            with output_area:
                _print_review_metrics()
            return

        row      = state["rows"].iloc[state["idx"]]
        sentence = row["sentence"]
        theme    = row.get("theme", "unknown")
        color    = THEME_PALETTE.get(theme, "#888780")
        total    = len(state["rows"])

        sentence_display.value = (
            f"<div style='padding:12px; background:#1A1A2E; border-radius:6px; "
            f"color:white; font-size:15px; line-height:1.5'>{sentence}</div>"
        )
        theme_badge.value = (
            f"<span style='background:{color}; color:white; padding:3px 12px; "
            f"border-radius:12px; font-size:12px; font-weight:bold'>"
            f"{theme.replace('_', ' ')}</span>"
        )
        progress_info.value = (
            f"<span style='color:#aaaaaa; font-size:13px'>"
            f"Sentence <b>{state['idx'] + 1}</b> of <b>{total}</b> &nbsp;|&nbsp; "
            f"Kept: <b style='color:#1D9E75'>{state['kept']}</b> &nbsp; "
            f"Rejected: <b style='color:#E24B4A'>{state['rejected']}</b></span>"
        )
        notes_input.value = ""    # clear note field for each new sentence

    def record_decision(keep: bool):
        """Save the current decision to disk and advance to the next sentence."""
        if state["idx"] >= len(state["rows"]):
            return

        row      = state["rows"].iloc[state["idx"]]
        sentence = row["sentence"]
        theme    = row.get("theme", "unknown")
        notes    = notes_input.value.strip()
        status   = "approved" if keep else "rejected"

        # Write to candidates.csv immediately -- this is the disk persistence
        # that makes the session resumable after a Colab timeout or crash
        cand_df = pd.read_csv(CANDIDATES_FILE)
        cand_df.loc[cand_df["sentence"] == sentence, "status"] = status
        cand_df.to_csv(CANDIDATES_FILE, index=False)

        if keep:
            new_row = pd.DataFrame([{
                "sentence": sentence,
                "theme":    theme,
                "notes":    notes,
            }])
            state["approved_df"] = pd.concat(
                [state["approved_df"], new_row], ignore_index=True
            )
            state["approved_df"].to_csv(APPROVED_FILE, index=False)
            state["kept"] += 1
        else:
            state["rejected"] += 1

        state["idx"] += 1
        refresh()

    # Wire the buttons to the decision recorder
    keep_btn.on_click(lambda _: record_decision(True))
    reject_btn.on_click(lambda _: record_decision(False))

    # Render the initial state before displaying anything
    refresh()

    # Display the complete UI as a vertical stack of widgets
    display(widgets.VBox(
        [
            title,
            progress_info,
            widgets.HTML("<div style='margin:4px 0'></div>"),
            sentence_display,
            widgets.HTML("<div style='margin:4px 0'></div>"),
            theme_badge,
            widgets.HTML(
                "<span style='color:#aaaaaa; font-size:12px; margin-top:6px'>"
                "Optional note</span>"
            ),
            notes_input,
            widgets.HBox(
                [keep_btn, reject_btn],
                layout=widgets.Layout(gap="12px", margin="8px 0 0 0"),
            ),
            output_area,
        ],
        layout=widgets.Layout(
            padding="16px",
            background_color="#0F0F1A",
            border="1px solid #333",
            border_radius="8px",
        ),
    ))

    return state["approved_df"]


# ── Review metrics (printed to console) ──────────────────────────────────────
def _print_review_metrics():
    try:
        cands = pd.read_csv(CANDIDATES_FILE)
    except FileNotFoundError:
        return

    print("\n" + "=" * 52)
    print("QUALITY REVIEW METRICS")
    print("=" * 52)

    theme_names    = [t["name"] for t in THEMES]
    total_reviewed = total_kept = total_rejected = 0

    for t in theme_names:
        sub      = cands[cands["theme"] == t]
        kept     = int((sub["status"] == "approved").sum())
        rejected = int((sub["status"] == "rejected").sum())
        reviewed = kept + rejected
        rate     = (rejected / reviewed * 100) if reviewed > 0 else 0.0
        total_reviewed += reviewed
        total_kept     += kept
        total_rejected += rejected
        bar = "█" * kept + "░" * rejected
        print(
            f"  {t:<20} kept {kept:>2}  rejected {rejected:>2}  "
            f"error rate {rate:5.1f}%  [{bar}]"
        )

    overall_rate = (
        (total_rejected / total_reviewed * 100) if total_reviewed > 0 else 0.0
    )
    print(
        f"\n  {'OVERALL':<20} kept {total_kept:>2}  rejected {total_rejected:>2}  "
        f"error rate {overall_rate:5.1f}%"
    )
    print("=" * 52)

    # Theme drift heuristic
    drift_keywords = {
        "sport":          ["goal", "score", "match", "team", "player", "rugby",
                           "cricket", "basketball", "stadium", "league"],
        "health":         ["hospital", "doctor", "malaria", "vaccine", "medicine",
                           "gym", "sick", "blood", "drug", "prescription"],
        "finance":        ["bank", "money", "loan", "transfer", "salary", "owo",
                           "market", "profit", "invest", "kuda", "opay"],
        "general":        ["family", "church", "wedding", "cook", "house", "baby",
                           "school", "brother", "sister", "celebrate"],
        "school_subjects":["biology", "chemistry", "math", "physics", "psychology",
                           "class", "experiment", "formula", "lesson", "teacher"],
    }

    approved    = cands[cands["status"] == "approved"]
    drift_found = False
    for _, row in approved.iterrows():
        assigned = row.get("theme", "")
        text     = str(row["sentence"]).lower()
        for other, kws in drift_keywords.items():
            if other == assigned:
                continue
            if any(kw in text for kw in kws):
                if not drift_found:
                    print("\n  Possible theme drift (review manually):")
                    drift_found = True
                print(f"    [{assigned} -> {other}?] {row['sentence']}")
    if not drift_found:
        print("\n  No obvious theme drift detected.")

    _plot_review_infographic(cands)


# ── Review infographic ────────────────────────────────────────────────────────
def _plot_review_infographic(cands: pd.DataFrame):
    theme_names     = [t["name"] for t in THEMES]
    kept_counts     = []
    rejected_counts = []
    for t in theme_names:
        sub = cands[cands["theme"] == t]
        kept_counts.append(int((sub["status"] == "approved").sum()))
        rejected_counts.append(int((sub["status"] == "rejected").sum()))

    total_kept     = sum(kept_counts)
    total_rejected = sum(rejected_counts)
    kept_color     = "#1D9E75"
    rejected_color = "#E24B4A"

    fig = plt.figure(figsize=(22, 7))
    fig.patch.set_facecolor("#0F0F1A")
    gs = gridspec.GridSpec(1, 3, figure=fig, wspace=0.35)
    ax_bar     = fig.add_subplot(gs[0])
    ax_donuts  = fig.add_subplot(gs[1])
    ax_stacked = fig.add_subplot(gs[2])
    for ax in (ax_bar, ax_stacked):
        dark_ax(ax)
    ax_donuts.set_facecolor("#0F0F1A")
    ax_donuts.axis("off")

    # Panel A: grouped bar chart
    x      = np.arange(len(theme_names))
    width  = 0.38
    bars_k = ax_bar.bar(
        x - width / 2, kept_counts, width,
        color=kept_color, edgecolor="#0F0F1A", linewidth=1.2, label="Kept"
    )
    bars_r = ax_bar.bar(
        x + width / 2, rejected_counts, width,
        color=rejected_color, edgecolor="#0F0F1A", linewidth=1.2, label="Rejected"
    )
    for bar in list(bars_k) + list(bars_r):
        v = int(bar.get_height())
        if v > 0:
            ax_bar.text(
                bar.get_x() + bar.get_width() / 2, v + 0.1,
                str(v), ha="center", va="bottom", color="white", fontsize=10
            )
    ax_bar.set_xticks(x)
    ax_bar.set_xticklabels([t.replace("_", "\n") for t in theme_names], fontsize=9)
    ax_bar.set_ylabel("Number of sentences", fontsize=10)
    ax_bar.set_title("Kept vs rejected per theme",
                     fontsize=12, fontweight="bold", color="white", pad=10)
    ax_bar.set_ylim(0, SENTENCES_PER_THEME + 1.5)
    ax_bar.axhline(SENTENCES_PER_THEME, color="#555", linewidth=0.8,
                   linestyle="--", alpha=0.6)
    ax_bar.text(
        len(theme_names) - 0.5, SENTENCES_PER_THEME + 0.15,
        f"Max ({SENTENCES_PER_THEME})", color="#888", fontsize=8, ha="right"
    )
    ax_bar.legend(fontsize=9, facecolor="#1A1A2E", labelcolor="white",
                  edgecolor="#444", loc="upper right")

    # Panel B: donut charts
    n         = len(theme_names)
    donut_w   = 1.0 / n
    donut_gap = 0.02
    ax_donuts.set_xlim(0, 1)
    ax_donuts.set_ylim(0, 1)
    ax_donuts.set_title("Success rate per theme",
                        fontsize=12, fontweight="bold", color="white", pad=10)

    for i, (name, kept, rejected) in enumerate(
            zip(theme_names, kept_counts, rejected_counts)):
        total    = kept + rejected
        kept_pct = (kept / total * 100) if total > 0 else 0
        left     = i * donut_w + donut_gap
        pos      = ax_donuts.get_position()
        ax_in    = fig.add_axes([
            pos.x0 + left * pos.width,
            pos.y0 + 0.12 * pos.height,
            (donut_w - donut_gap * 2) * pos.width,
            0.76 * pos.height,
        ])
        ax_in.set_facecolor("#0F0F1A")
        ax_in.axis("off")
        wedge_colors = [
            kept_color,
            rejected_color if (100 - kept_pct) > 0 else "#1A1A2E"
        ]
        ax_in.pie(
            [kept_pct, max(0, 100 - kept_pct)],
            colors=wedge_colors,
            startangle=90, counterclock=False,
            wedgeprops={"width": 0.45, "edgecolor": "#0F0F1A", "linewidth": 1.5},
        )
        ax_in.text(0,  0.05, f"{kept_pct:.0f}%",
                   ha="center", va="center", fontsize=11, fontweight="bold",
                   color="white", transform=ax_in.transData)
        ax_in.text(0, -0.25, f"{kept}/{total}",
                   ha="center", va="center", fontsize=8, color="#aaaaaa",
                   transform=ax_in.transData)
        ax_in.text(0, -0.72, name.replace("_", "\n"),
                   ha="center", va="top", fontsize=7.5, color="white",
                   transform=ax_in.transData)

    ax_donuts.legend(
        handles=[
            Patch(facecolor=kept_color,     label="Kept"),
            Patch(facecolor=rejected_color, label="Rejected"),
        ],
        fontsize=9, facecolor="#1A1A2E", labelcolor="white", edgecolor="#444",
        loc="lower center", bbox_to_anchor=(0.5, -0.04), ncol=2,
    )

    # Panel C: stacked 100% bar chart
    all_names  = theme_names + ["OVERALL"]
    all_kept   = kept_counts  + [total_kept]
    all_reject = rejected_counts + [total_rejected]
    all_totals = [k + r for k, r in zip(all_kept, all_reject)]
    kept_pcts  = [k / t * 100 if t > 0 else 0 for k, t in zip(all_kept,   all_totals)]
    rej_pcts   = [r / t * 100 if t > 0 else 0 for r, t in zip(all_reject, all_totals)]
    x2         = np.arange(len(all_names))
    b1 = ax_stacked.bar(x2, kept_pcts, color=kept_color,
                        edgecolor="#0F0F1A", linewidth=1.2, label="Kept %")
    b2 = ax_stacked.bar(x2, rej_pcts, bottom=kept_pcts, color=rejected_color,
                        edgecolor="#0F0F1A", linewidth=1.2, label="Rejected %")
    for i, (kp, rp) in enumerate(zip(kept_pcts, rej_pcts)):
        if kp >= 12:
            ax_stacked.text(i, kp / 2, f"{kp:.0f}%",
                            ha="center", va="center", color="white",
                            fontsize=8, fontweight="bold")
        if rp >= 12:
            ax_stacked.text(i, kp + rp / 2, f"{rp:.0f}%",
                            ha="center", va="center", color="white",
                            fontsize=8, fontweight="bold")
    for patch in [b1[-1], b2[-1]]:
        patch.set_edgecolor("#ffffff")
        patch.set_linewidth(1.8)
    ax_stacked.set_xticks(x2)
    ax_stacked.set_xticklabels(
        [t.replace("_", "\n") for t in theme_names] + ["OVERALL"], fontsize=9
    )
    ax_stacked.set_ylim(0, 100)
    ax_stacked.set_ylabel("Proportion (%)", fontsize=10)
    ax_stacked.set_title("Keep / reject proportion\n(normalised to 100%)",
                         fontsize=12, fontweight="bold", color="white", pad=10)
    ax_stacked.axhline(50, color="#555", linewidth=0.8, linestyle="--", alpha=0.5)
    ax_stacked.legend(fontsize=9, facecolor="#1A1A2E", labelcolor="white",
                      edgecolor="#444", loc="lower right")

    fig.suptitle(
        f"Quality Review Report  --  {total_kept} kept / "
        f"{total_rejected} rejected / {total_kept + total_rejected} total",
        fontsize=14, fontweight="bold", color="white", y=1.02,
    )
    plt.savefig("quality_review_report.png", dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    plt.show()
    print("Saved to 'quality_review_report.png'.")
    print("Next step: run Cell 5 (NER + POS annotation).")


# ── Run ──────────────────────────────────────────────────────
approved_df = launch_rating_ui()

# Safety reload from disk in case the session was interrupted mid-review.
# Because every decision is written to disk on each click, nothing is lost.
try:
    approved_df = pd.read_csv(APPROVED_FILE)
    print(f"\n{len(approved_df)} sentences in approved_sentences.csv.")
except FileNotFoundError:
    print("No approved sentences yet. Complete the review above first.")

# ============================================================
# CELL 3 — Semantic space visualisation
# ============================================================
# Prerequisites : Cell 1 has been run this session
# Reads         : candidates.csv
# Writes        : semantic_space.png
#
# Produces a two-panel figure:
#   Left  -- UMAP scatter of all sentences coloured by theme.
#            Sentences that are semantically similar cluster
#            together. Well-separated clusters mean themes are
#            genuinely topically distinct.
#   Right -- Intra-theme mean cosine distance bar chart.
#            Higher bar = more diverse sentences within that
#            theme. A very low bar signals near-duplicates.
# ============================================================

def visualise_semantic_space():
    # Read from disk -- no dependency on Cell 2 being in memory
    try:
        candidates_df = pd.read_csv(CANDIDATES_FILE)
    except FileNotFoundError:
        print("candidates.csv not found. Run Cell 2 first.")
        return

    sentences = candidates_df["sentence"].tolist()
    if len(sentences) < 4:
        print("Need at least 4 sentences to plot. Run Cell 2 first.")
        return

    themes = (
        candidates_df["theme"].tolist()
        if "theme" in candidates_df.columns
        else ["unknown"] * len(sentences)
    )

    print("Encoding sentences with multilingual model...")
    model       = get_embedding_model()
    embeddings  = model.encode(sentences, show_progress_bar=True)
    sim_matrix  = cosine_similarity(embeddings)
    dist_matrix = 1.0 - sim_matrix  # cosine distance (0=identical, 1=opposite)

    print("Running UMAP projection to 2D...")
    reducer   = UMAP(n_neighbors=min(10, len(sentences) - 1),
                     min_dist=0.15, random_state=42)
    coords_2d = reducer.fit_transform(embeddings)

    unique_themes = sorted(set(themes))

    # Per-theme mean pairwise cosine distance
    theme_mean_dist = {}
    for t in unique_themes:
        idx = [i for i, th in enumerate(themes) if th == t]
        if len(idx) >= 2:
            sub   = dist_matrix[np.ix_(idx, idx)]
            upper = sub[np.triu_indices(len(idx), k=1)]
            theme_mean_dist[t] = float(upper.mean())

    fig = plt.figure(figsize=(20, 8))
    fig.patch.set_facecolor("#0F0F1A")
    gs  = gridspec.GridSpec(1, 2, width_ratios=[3, 2], figure=fig)
    ax_scatter = fig.add_subplot(gs[0])
    ax_bar     = fig.add_subplot(gs[1])
    dark_ax(ax_scatter)
    dark_ax(ax_bar)

    # Left panel: UMAP scatter coloured by theme
    for t in unique_themes:
        idx = np.array([i for i, th in enumerate(themes) if th == t])
        ax_scatter.scatter(
            coords_2d[idx, 0], coords_2d[idx, 1],
            c=THEME_PALETTE.get(t, "#888780"), s=90, zorder=3,
            label=t.replace("_", " "), edgecolors="#0F0F1A", linewidths=0.8,
        )
    for i, sentence in enumerate(sentences):
        short = " ".join(sentence.split()[:4]) + "..."
        ax_scatter.annotate(short,
            xy=(coords_2d[i, 0], coords_2d[i, 1]),
            xytext=(5, 5), textcoords="offset points",
            fontsize=7, color="white", alpha=0.65, zorder=5)
    ax_scatter.legend(fontsize=9, facecolor="#1A1A2E", labelcolor="white",
                      edgecolor="#444", loc="upper left", framealpha=0.9)
    ax_scatter.set_title(
        f"UMAP semantic space -- {len(sentences)} sentences, {len(unique_themes)} themes",
        fontsize=12, fontweight="bold", color="white", pad=12)
    ax_scatter.set_xlabel("UMAP dimension 1", fontsize=10)
    ax_scatter.set_ylabel("UMAP dimension 2", fontsize=10)

    # Right panel: intra-theme cosine distance bar chart
    if theme_mean_dist:
        bar_themes = list(theme_mean_dist.keys())
        bar_values = [theme_mean_dist[t] for t in bar_themes]
        bar_colors = [THEME_PALETTE.get(t, "#888780") for t in bar_themes]
        bars = ax_bar.barh(
            [t.replace("_", " ") for t in bar_themes], bar_values,
            color=bar_colors, edgecolor="#0F0F1A", linewidth=1.2)
        for bar, val in zip(bars, bar_values):
            ax_bar.text(val + 0.003, bar.get_y() + bar.get_height() / 2,
                        f"{val:.3f}", va="center", ha="left",
                        color="white", fontsize=9)
        all_upper   = dist_matrix[np.triu_indices(len(sentences), k=1)]
        corpus_mean = float(all_upper.mean())
        ax_bar.axvline(corpus_mean, color="#888780", linewidth=1.0,
                       linestyle="--", alpha=0.7,
                       label=f"Corpus mean: {corpus_mean:.3f}")
        ax_bar.legend(fontsize=8, facecolor="#1A1A2E", labelcolor="white",
                      edgecolor="#444", framealpha=0.9)
        ax_bar.set_title("Intra-theme diversity\n(mean pairwise cosine distance)",
                         fontsize=12, fontweight="bold", color="white", pad=12)
        ax_bar.set_xlabel("Mean cosine distance (higher = more diverse)", fontsize=10)
        ax_bar.set_xlim(0, max(bar_values) * 1.25)
        ax_bar.text(0.98, 0.03,
                    "Higher = more spread out\nLower = more similar",
                    transform=ax_bar.transAxes, fontsize=8, color="#aaaaaa",
                    ha="right", va="bottom",
                    bbox=dict(boxstyle="round,pad=0.3", facecolor="#2A2A3E",
                              edgecolor="#555", alpha=0.85))

        print("\nIntra-theme mean cosine distances:")
        for t, d in sorted(theme_mean_dist.items(), key=lambda x: x[1]):
            bar_str = "█" * int(d * 80)
            print(f"  {t:<20} {d:.4f}  {bar_str}")

    fig.suptitle("Semantic space analysis -- Yoruba-English code-switched candidates",
                 fontsize=14, fontweight="bold", color="white", y=1.01)
    plt.tight_layout()
    plt.savefig("semantic_space.png", dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    plt.show()
    print("\nSaved to 'semantic_space.png'.")
    print("Next step: run Cell 4 (human quality review).")

# ── Run ──────────────────────────────────────────────────────
visualise_semantic_space()

"""**isues with generated data**
- no diacritics on yoruba word
- sytaxx isnt that great
- NG Pidgin mixture as CS esp. with finance data (1) Tunde, shey GTBank don approve your loan application? (2) Bola, na so so wahala PalmPay dey give me for transfer. (3--combines all 3 lang. ) Temi, won ti so fun e pe show eleyi na the latest for DSTV?
"""

# ============================================================
# CELL 5 — Combined NER + POS annotation
# ============================================================
# Prerequisites : Cell 1 has been run this session
# Reads         : approved_sentences.csv
# Writes        : ner_output.csv, pos_output.csv
#
# Sends all approved sentences to GPT-4 in batches of 10.
# Each batch is a SINGLE API call that returns both NER entity
# labels and POS tags simultaneously -- halving the number of
# API calls and cutting annotation cost by ~50% compared to
# running NER and POS in separate passes.
#
# If ner_output.csv already exists from a previous run, this
# cell skips re-annotation and just loads the existing files.
# ============================================================

def run_annotation():
    # Skip if already done
    if os.path.exists(NER_FILE) and os.path.exists(POS_FILE):
        df_ner = pd.read_csv(NER_FILE)
        df_pos = pd.read_csv(POS_FILE)
        print(f"Annotation already complete.")
        print(f"  NER: {len(df_ner)} entity records in '{NER_FILE}'")
        print(f"  POS: {len(df_pos)} token records in '{POS_FILE}'")
        print("Next step: run Cell 6 (NER verification).")
        return df_ner, df_pos

    try:
        approved_df = pd.read_csv(APPROVED_FILE)
    except FileNotFoundError:
        print("approved_sentences.csv not found. Run Cell 4 first.")
        return None, None

    if approved_df.empty:
        print("No approved sentences found. Complete Cell 4 first.")
        return None, None

    print(f"Annotating {len(approved_df)} sentences (NER + POS, single API pass)...")
    ner_records, pos_records = [], []
    batch_size   = 10
    sentence_list = approved_df["sentence"].tolist()
    batches = [sentence_list[i:i + batch_size]
               for i in range(0, len(sentence_list), batch_size)]

    for batch in tqdm(batches, desc="Annotating batches"):
        formatted = "\n".join(f"- {s}" for s in batch)
        messages  = annotation_prompt.format_messages(sentences=formatted)
        output    = call_llm(messages)
        if output is None:
            continue
        try:
            data = parse_json_output(output)
            for item in data:
                sent = item["sentence"]
                for ent in item.get("entities", []):
                    ner_records.append({"sentence": sent, "word": ent["word"],
                                        "entity_label": ent["label"]})
                for tag in item.get("pos_tags", []):
                    pos_records.append({"sentence": sent, "word": tag["word"],
                                        "pos_tag": tag["pos"]})
        except Exception as e:
            print(f"  Parse error on batch: {e}")
            time.sleep(2)

    df_ner = pd.DataFrame(ner_records)
    df_pos = pd.DataFrame(pos_records)
    df_ner.to_csv(NER_FILE, index=False)
    df_pos.to_csv(POS_FILE, index=False)
    print(f"\nDone.")
    print(f"  NER: {len(df_ner)} entity records saved to '{NER_FILE}'")
    print(f"  POS: {len(df_pos)} token records saved to '{POS_FILE}'")
    print("Next step: run Cell 6 (NER verification).")
    return df_ner, df_pos

# ── Run ──────────────────────────────────────────────────────
df_ner, df_pos = run_annotation()

# ============================================================
# CELL 6 — Human NER verification + error metrics + infographic
# ============================================================
# Prerequisites : Cell 1 has been run this session
# Reads         : ner_output.csv
# Writes        : ner_verified.csv  (updated after every click)
#                 ner_verification_report.png
#
# Uses ipywidgets so the UI renders directly inside the cell
# with no URL, no tunnel, and no loading wait.
#
# For each entity GPT-4 predicted, the sentence is shown with
# the entity word bracketed so you can see it in context.
# You choose: Correct, Wrong label, or Not an entity.
#
# Both the human label and GPT-4's original label are saved
# side by side so you can compute agreement rates later.
# The original ner_output.csv is never modified.
#
# The session is fully resumable -- already-verified pairs are
# skipped on reload so a dropped session loses at most one decision.
# Metrics and the infographic fire automatically on completion.
# ============================================================

import ipywidgets as widgets
from IPython.display import display

VALID_LABELS = ["PERSON", "LOCATION", "ORGANIZATION"]

def launch_ner_verification_ui():

    try:
        df_ner = pd.read_csv(NER_FILE)
    except FileNotFoundError:
        print("ner_output.csv not found. Run Cell 5 first.")
        return None

    try:
        verified_df  = pd.read_csv(NER_VERIFIED_FILE)
        already_done = set(zip(verified_df["sentence"], verified_df["word"]))
        print(f"Loaded {len(verified_df)} previously verified entities.")
    except FileNotFoundError:
        verified_df  = pd.DataFrame(
            columns=["sentence", "word", "entity_label", "gpt_label", "status"]
        )
        already_done = set()

    # Build the review queue -- skip any pair already verified in a prior session
    pairs = [
        (row["sentence"], row["word"], row["entity_label"])
        for _, row in df_ner.iterrows()
        if (row["sentence"], row["word"]) not in already_done
    ]

    if not pairs:
        print("All NER entities already verified.")
        df_v = pd.read_csv(NER_VERIFIED_FILE)
        _print_ner_metrics(df_v)
        _plot_ner_distribution(df_v)
        return df_v

    state = {"idx": 0, "pairs": pairs, "verified_df": verified_df}

    # ── Widget layout ─────────────────────────────────────────────────────────
    title = widgets.HTML(
        "<h3 style='margin:0 0 4px 0; color:#e0e0e0'>NER Label Verification</h3>"
        "<p style='margin:0 0 12px 0; color:#aaaaaa; font-size:13px'>"
        "The <b>bracketed word</b> is the entity GPT-4 predicted. "
        "Confirm the label, correct it, or mark it as not an entity at all.</p>"
    )

    sentence_display = widgets.HTML()
    gpt_label_display = widgets.HTML()
    progress_display  = widgets.HTML()

    decision_toggle = widgets.ToggleButtons(
        options=["Correct", "Wrong label", "Not an entity"],
        value="Correct",
        button_style="",
        style={"button_width": "140px"},
    )

    correction_dropdown = widgets.Dropdown(
        options=VALID_LABELS,
        description="Correct label:",
        style={"description_width": "100px"},
        layout=widgets.Layout(width="280px"),
    )
    # Show the correction dropdown only when "Wrong label" is selected
    correction_dropdown.layout.visibility = "hidden"

    def toggle_correction(change):
        correction_dropdown.layout.visibility = (
            "visible" if change["new"] == "Wrong label" else "hidden"
        )
    decision_toggle.observe(toggle_correction, names="value")

    submit_btn = widgets.Button(
        description="Submit",
        button_style="primary",
        layout=widgets.Layout(width="120px", height="40px"),
    )

    output_area = widgets.Output()

    def refresh():
        """Update displayed values to show the current entity in the queue."""
        if state["idx"] >= len(state["pairs"]):
            sentence_display.value = (
                "<div style='padding:12px; background:#1A3A1A; border-radius:6px; "
                "color:#1D9E75; font-size:15px; font-weight:bold'>"
                "All entities verified!</div>"
            )
            gpt_label_display.value  = ""
            progress_display.value   = (
                f"<span style='color:#aaaaaa; font-size:13px'>"
                f"All {len(state['pairs'])} entities reviewed.</span>"
            )
            submit_btn.disabled             = True
            decision_toggle.disabled        = True
            correction_dropdown.disabled    = True
            with output_area:
                # Reload from disk to get full accumulated result across sessions
                try:
                    df_final = pd.read_csv(NER_VERIFIED_FILE)
                except FileNotFoundError:
                    df_final = state["verified_df"]
                _print_ner_metrics(df_final)
                _plot_ner_distribution(df_final)
            return

        sent, word, gpt_label = state["pairs"][state["idx"]]
        # Bracket the entity word so it stands out clearly in its sentence context
        highlighted = sent.replace(word, f"<b style='color:#E9C46A'>[ {word} ]</b>")
        total       = len(state["pairs"])

        sentence_display.value = (
            f"<div style='padding:12px; background:#1A1A2E; border-radius:6px; "
            f"color:white; font-size:15px; line-height:1.6'>{highlighted}</div>"
        )
        gpt_label_display.value = (
            f"<span style='color:#aaaaaa; font-size:13px'>GPT-4 predicted: </span>"
            f"<span style='background:#264653; color:white; padding:2px 10px; "
            f"border-radius:10px; font-size:13px; font-weight:bold'>{gpt_label}</span>"
        )
        progress_display.value = (
            f"<span style='color:#aaaaaa; font-size:13px'>"
            f"Entity <b>{state['idx'] + 1}</b> of <b>{total}</b></span>"
        )
        # Reset controls for the new entity
        decision_toggle.value               = "Correct"
        correction_dropdown.layout.visibility = "hidden"

    def submit_decision(_):
        """Record the current decision and advance to the next entity."""
        if state["idx"] >= len(state["pairs"]):
            return

        sent, word, gpt_label = state["pairs"][state["idx"]]
        decision = decision_toggle.value

        if decision == "Not an entity":
            # GPT-4 hallucinated this entity -- exclude it from the verified set
            final_label = None
            status      = "rejected"
        elif decision == "Wrong label":
            final_label = correction_dropdown.value
            status      = "corrected"
        else:
            final_label = gpt_label
            status      = "confirmed"

        if final_label is not None:
            new_row = pd.DataFrame([{
                "sentence":     sent,
                "word":         word,
                "entity_label": final_label,   # human-adjudicated, used in analysis
                "gpt_label":    gpt_label,     # GPT-4 original, kept for agreement calc
                "status":       status,
            }])
            state["verified_df"] = pd.concat(
                [state["verified_df"], new_row], ignore_index=True
            )
            # Write to disk immediately on every decision
            state["verified_df"].to_csv(NER_VERIFIED_FILE, index=False)

        state["idx"] += 1
        refresh()

    submit_btn.on_click(submit_decision)

    # Initial display render
    refresh()

    display(widgets.VBox(
        [
            title,
            progress_display,
            widgets.HTML("<div style='margin:4px 0'></div>"),
            sentence_display,
            widgets.HTML("<div style='margin:6px 0'></div>"),
            gpt_label_display,
            widgets.HTML("<div style='margin:8px 0'></div>"),
            decision_toggle,
            correction_dropdown,
            widgets.HTML("<div style='margin:4px 0'></div>"),
            submit_btn,
            output_area,
        ],
        layout=widgets.Layout(
            padding="16px",
            border="1px solid #333",
            border_radius="8px",
        ),
    ))

    # Reload verified entities from disk to return the full accumulated result
    try:
        return pd.read_csv(NER_VERIFIED_FILE)
    except FileNotFoundError:
        return state["verified_df"]


# ── NER metrics ───────────────────────────────────────────────────────────────
def _print_ner_metrics(df_verified: pd.DataFrame):
    if df_verified.empty:
        print("No verified entities to report on.")
        return

    total       = len(df_verified)
    confirmed   = int((df_verified["status"] == "confirmed").sum())
    corrected   = int((df_verified["status"] == "corrected").sum())
    rejected    = int((df_verified["status"] == "rejected").sum())
    accuracy    = confirmed  / total * 100 if total > 0 else 0
    halluc_rate = rejected   / total * 100 if total > 0 else 0
    corr_rate   = corrected  / total * 100 if total > 0 else 0

    print("\n" + "=" * 52)
    print("NER VERIFICATION METRICS")
    print("=" * 52)
    print(f"  Total entities reviewed  : {total}")
    print(f"  Confirmed (correct)      : {confirmed}  ({accuracy:.1f}%)")
    print(f"  Corrected (wrong label)  : {corrected}  ({corr_rate:.1f}%)")
    print(f"  Rejected (hallucinated)  : {rejected}  ({halluc_rate:.1f}%)")
    print(f"\n  GPT-4 NER accuracy       : {accuracy:.1f}%")
    print(f"  GPT-4 NER error rate     : {100 - accuracy:.1f}%")

    print("\n  Per-label accuracy (grouped by GPT-4 prediction):")
    for label in VALID_LABELS:
        sub     = df_verified[df_verified["gpt_label"] == label]
        n       = len(sub)
        correct = int((sub["status"] == "confirmed").sum())
        rate    = correct / n * 100 if n > 0 else 0
        print(f"    {label:<14} n={n:>3}  accuracy {rate:5.1f}%")

    non_rej = df_verified[df_verified["status"] != "rejected"]
    if len(non_rej) > 0:
        agreement = (non_rej["gpt_label"] == non_rej["entity_label"]).mean() * 100
        print(f"\n  Label agreement (non-hallucinated): {agreement:.1f}%")
    print("=" * 52)


# ── NER distribution infographic ─────────────────────────────────────────────
def _plot_ner_distribution(df_verified: pd.DataFrame):
    if df_verified.empty:
        print("No verified data to plot.")
        return

    label_colors  = {"PERSON": "#2E86AB", "LOCATION": "#A23B72",
                     "ORGANIZATION": "#F18F01"}
    status_colors = {"confirmed": "#1D9E75", "corrected": "#E9C46A",
                     "rejected": "#E24B4A"}

    fig, axes = plt.subplots(1, 3, figsize=(20, 6))
    fig.patch.set_facecolor("#0F0F1A")
    for ax in axes:
        dark_ax(ax)

    # Panel A: verified label distribution
    verified_kept = df_verified[df_verified["status"] != "rejected"]
    label_counts  = verified_kept["entity_label"].value_counts()
    bars = axes[0].bar(
        label_counts.index, label_counts.values,
        color=[label_colors.get(l, "#888780") for l in label_counts.index],
        edgecolor="#0F0F1A", linewidth=1.5,
    )
    axes[0].set_title("Verified entity distribution\n(human-adjudicated labels)",
                      fontsize=12, fontweight="bold", pad=10)
    axes[0].set_xlabel("Entity label", fontsize=10)
    axes[0].set_ylabel("Count", fontsize=10)
    for bar, val in zip(bars, label_counts.values):
        axes[0].text(
            bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.2,
            str(val), ha="center", va="bottom", color="white", fontsize=10
        )

    # Panel B: status breakdown per GPT-4 label
    status_pivot = (
        df_verified.groupby(["gpt_label", "status"])
        .size().unstack(fill_value=0)
        .reindex(columns=["confirmed", "corrected", "rejected"], fill_value=0)
    )
    bottom_vals = np.zeros(len(status_pivot))
    for col in ["confirmed", "corrected", "rejected"]:
        if col in status_pivot.columns:
            axes[1].barh(
                status_pivot.index, status_pivot[col],
                left=bottom_vals, color=status_colors[col],
                label=col, edgecolor="#0F0F1A", linewidth=0.8,
            )
            bottom_vals += status_pivot[col].values
    axes[1].set_title("GPT-4 prediction status\nper entity type",
                      fontsize=12, fontweight="bold", pad=10)
    axes[1].set_xlabel("Count", fontsize=10)
    axes[1].legend(fontsize=9, facecolor="#1A1A2E", labelcolor="white",
                   edgecolor="#444", loc="lower right")

    # Panel C: label confusion matrix
    labels_order = ["PERSON", "LOCATION", "ORGANIZATION"]
    non_rej      = df_verified[df_verified["status"] != "rejected"]
    confusion    = pd.crosstab(
        non_rej["gpt_label"], non_rej["entity_label"],
        rownames=["GPT-4 predicted"], colnames=["Human label"]
    ).reindex(index=labels_order, columns=labels_order, fill_value=0)

    axes[2].imshow(confusion.values, cmap="Blues", aspect="auto")
    axes[2].set_xticks(range(len(labels_order)))
    axes[2].set_yticks(range(len(labels_order)))
    axes[2].set_xticklabels(labels_order, fontsize=9, color="white")
    axes[2].set_yticklabels(labels_order, fontsize=9, color="white")
    axes[2].set_xlabel("Human label", fontsize=10)
    axes[2].set_ylabel("GPT-4 predicted", fontsize=10)
    axes[2].set_title("Label confusion matrix\n(non-hallucinated predictions)",
                      fontsize=12, fontweight="bold", pad=10)
    max_val = confusion.values.max() if confusion.values.max() > 0 else 1
    for i in range(len(labels_order)):
        for j in range(len(labels_order)):
            val = confusion.values[i, j]
            axes[2].text(
                j, i, str(val), ha="center", va="center", fontsize=11,
                fontweight="bold",
                color="white" if val > max_val * 0.5 else "#aaaaaa",
            )

    fig.suptitle("NER Verification Report -- Yoruba-English Code-Switched Corpus",
                 fontsize=14, fontweight="bold", color="white", y=1.02)
    plt.tight_layout()
    plt.savefig("ner_verification_report.png", dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    plt.show()
    print("Saved to 'ner_verification_report.png'.")
    print("Next step: run Cell 7 (FastText language identification).")


# ── Run ──────────────────────────────────────────────────────
df_ner_verified = launch_ner_verification_ui()

# ============================================================
# CELL 7 — FastText word-level language identification
# ============================================================
# Prerequisites : Cell 1 has been run this session
# Reads         : approved_sentences.csv
# Writes        : langid_output.csv
#
# Tags every token in each approved sentence as Yoruba (yo),
# English (en), or other. Uses the FastText lid.176.bin model
# which runs locally -- no API call and no cost.
#
# The model is automatically downloaded if it is not already
# present in the Colab working directory.
#
# If langid_output.csv already exists, this cell loads it and
# skips re-tagging.
#
# NumPy 2.x compatibility note:
# FastText's internal predict() method uses np.array(probs, copy=False),
# which raises a ValueError in NumPy 2.x because the semantics of copy=False
# changed -- it now means "raise an error if a copy is unavoidable" rather
# than "avoid a copy if you can". The patch below replaces np.array inside
# the fasttext module with a wrapper that silently removes the copy=False
# argument before forwarding the call, restoring the NumPy 1.x behaviour
# without downgrading or reinstalling anything.
# ============================================================

def _patch_fasttext_for_numpy2():
    """
    Apply a one-time monkey-patch so FastText works with NumPy 2.x.

    FastText calls np.array(probs, copy=False) inside predict(). In NumPy 2.x
    this raises: "ValueError: Unable to avoid copy while creating an array as
    requested." The fix is to replace np.array inside the fasttext.FastText
    module with a thin wrapper that strips the copy keyword before forwarding
    to the real np.array. This has no effect on NumPy 1.x runtimes.
    """
    import numpy as _np
    import fasttext.FastText as _ft_module

    _real_array = _np.array

    def _patched_array(obj, *args, **kwargs):
        # Remove the copy keyword that NumPy 2.x no longer accepts with False
        kwargs.pop("copy", None)
        return _real_array(obj, *args, **kwargs)

    # Inject the patched version into the fasttext module's numpy namespace
    _ft_module.np.array = _patched_array

_patch_fasttext_for_numpy2()


def run_language_identification():
    # Skip if already done
    if os.path.exists(LANGID_FILE):
        df_langid = pd.read_csv(LANGID_FILE)
        print(f"Language ID already complete: {len(df_langid)} token records in '{LANGID_FILE}'.")
        print("Next step: run Cell 8 (final visualisation).")
        return df_langid

    try:
        approved_df = pd.read_csv(APPROVED_FILE)
    except FileNotFoundError:
        print("approved_sentences.csv not found. Run Cell 4 first.")
        return None

    # Auto-download the FastText model if it is missing.
    # This is the fix for: ValueError: lid.176.bin cannot be opened!
    ensure_fasttext()

    print(f"Tagging {len(approved_df)} sentences with FastText language ID...")
    fasttext.FastText.eprint = lambda *a, **k: None   # suppress verbose output
    model   = fasttext.load_model(FASTTEXT_PATH)
    records = []

    for _, row in tqdm(approved_df.iterrows(), total=len(approved_df),
                       desc="Tagging tokens"):
        sentence = row["sentence"]
        for word in sentence.split():
            labels, probs = model.predict(word, k=1)
            lang          = labels[0].replace("__label__", "")  # e.g. "yo", "en"
            # Collapse everything that is not Yoruba or English into 'other'
            # so visualisations remain clean and interpretable
            simplified    = lang if lang in ("yo", "en") else "other"
            records.append({
                "sentence":   sentence,
                "word":       word,
                "lang_raw":   lang,        # full FastText prediction preserved
                "lang":       simplified,  # yo / en / other
                "confidence": round(float(probs[0]), 3),
            })

    df_langid = pd.DataFrame(records)
    df_langid.to_csv(LANGID_FILE, index=False)
    print(f"\nSaved {len(df_langid)} token records to '{LANGID_FILE}'.")
    print("Next step: run Cell 8 (final visualisation).")
    return df_langid

# ── Run ──────────────────────────────────────────────────────
df_langid = run_language_identification()

"ner_output.csv", "pos_output.csv", "ner_verified.csv",
              "langid_output.csv", "semantic_space.png",
              "quality_review_report.png", "ner_verification_report.png",
              "nlp_analysis.png"]:
        status = "present" if os.path.exists(f) else "MISSING"
        print(f"  {f:<38} {status}")

# ── Run ──────────────────────────────────────────────────────
visualise_final()
